services:
  # Vue.js Application Build
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    container_name: memorial-app
    volumes:
      - app-dist:/app/dist
    networks:
      - memorial-network
    command: ['sh', '-c', "echo 'Build completed' && sleep 15 && tail -f /dev/null"]
    restart: 'no'

  # Nginx Web Server with REG.RU SSL
  nginx:
    image: nginx:alpine
    container_name: memorial-nginx
    ports:
      - '80:80' # HTTP
      - '443:443' # HTTPS
    volumes:
      - app-dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro # Fixed: Mount nginx/ssl directory
      - nginx-logs:/var/log/nginx
    depends_on:
      app:
        condition: service_started
    restart: unless-stopped
    networks:
      - memorial-network
    command:
      [
        'sh',
        '-c',
        "sleep 20 && chown -R nginx:nginx /usr/share/nginx/html && chmod -R 755 /usr/share/nginx/html && nginx -g 'daemon off;'",
      ]
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s
    environment:
      - TZ=Europe/Moscow

volumes:
  app-dist:
    driver: local
  nginx-logs:
    driver: local

networks:
  memorial-network:
    driver: bridge
